name: owari
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # flutter_native_splash: ^2.3.0

# flutter_native_splash:
#   image: assets/logo1.png

#   color: "#f9f9f9"

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/1.jpg
  # fonts:
  #   - family: MonumentExtended
  #     fonts:
  #       - asset: assets/font/MonumenExtended-Reguler.otf
